In [1]:
import pandas as pd

df_csv = pd.read_csv("test_Y3wMUE5_7gLdaTN.csv")

print("CSV Dataset:")
display(df_csv.head())

CSV Dataset:

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [2]:
df_excel = pd.read_excel(
    "Historicalinvesttemp.xlsx",
    sheet_name="Sheet1"
)

print("Excel Dataset:")
display(df_excel.head())

Excel Dataset:

  Unnamed: 0                     Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                            NaN        NaN        NaN
1        NaN                            NaN        NaN        NaN
2        NaN                            NaN        NaN        NaN
3        NaN  Annual Returns on Investments        NaN        NaN
4       Year                         Stocks    T.Bills    T.Bonds

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=15
)

response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

table = soup.find("table", class_="wikitable")

df_web = pd.read_html(str(table))[0]

print("Web table loaded successfully!")
print("Rows:", len(df_web))
print("Columns:", len(df_web.columns))

display(df_web.head())

Web table loaded successfully!
Rows: 222
Columns: 4

C:\Users\HDCO422146\AppData\Local\Temp\ipykernel_4616\992881860.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_web = pd.read_html(str(table))[0]

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,111565144
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211

In [8]:
df = pd.read_excel("Historicalinvesttemp.xlsx")

print("Excel Dataset:")
display(df.head())

Excel Dataset:

  Unnamed: 0                     Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                            NaN        NaN        NaN
1        NaN                            NaN        NaN        NaN
2        NaN                            NaN        NaN        NaN
3        NaN  Annual Returns on Investments        NaN        NaN
4       Year                         Stocks    T.Bills    T.Bonds

In [9]:
df.to_excel("weeeeee.xlsx", index=False)

print("File saved successfully as weeeeee.xlsx")

File saved successfully as weeeeee.xlsx